packages:
  - apps/user/*
  - apps/core/*
  - packages/*
  - packages/shared/*
  - tooling/*

catalog:
  "@biomejs/biome": ^1.9.4
  "@tsconfig/strictest": ^2.0.5
  "@types/node": ^22.13.9
  fix-esm-import-path: ^1.10.1
  rimraf: ^6.0.1
  sort-package-json: ^2.14.0
  tsc-alias: ^1.8.11
  tsup: ^8.4.0
  tsx: ^4.19.3
  typescript: ^5.8.2
